/*\
title: $:/plugins/tobibeer/preview/startup.js
type: application/javascript
module-type: startup

Enhances the link widget for on-hover previews

@preserve
\*/
(function(){"use strict";var e=require("$:/core/modules/widgets/link.js").link,t=e.prototype.render,p=e.prototype.handleClickEvent,i=require("$:/core/modules/utils/dom/popup.js").Popup,o=i.prototype.popupInfo;e.prototype.render=function(){t.apply(this,arguments);var e,p=this,i=this.wiki,o=this.domNodes[0],r=i.getTiddler(p.to),u="$:/plugins/tobibeer/preview/defaults/",n=$tw.utils.parseKeyDescriptor(i.getTextReference(u+"keys","").toUpperCase()),s=i.getTextReference(u+"delay","").toUpperCase(),l=function(){var t=$tw.popup.popupInfo(o).popupLevel;clearTimeout(e);$tw.popup.cancel(t-1);t++;i.setText("$:/temp/tobibeer/preview-"+t+"-tiddler","text",null,p.to);setTimeout(function(){$tw.popup.triggerPopup({domNode:o,title:"$:/temp/tobibeer/preview-"+t,wiki:i})},50)},a=function(){var e,t,r=1,n=i.getTextReference(u+"not","");if(n){$tw.utils.each(n.split(" "),function(e){var t=o;while(t&&r){if($tw.utils.hasClass(t,e)){r=0;return false}t=t.parentNode}})}t=i.getTextReference(u+"exclude","");e=t?i.filterTiddlers(t):[];if(e.indexOf(p.to)>=0){r=0}return r};s=s?parseInt(s):null;if(s!==null&&isNaN(s)){s=0}if(r){$tw.utils.addClass(o,"tc-popup-handle");$tw.utils.addClass(o,"tc-popup-absolute");["mouseover","mouseout"].forEach(function(t){o.addEventListener(t,function(p){var i=p||window.event;if(t==="mouseover"){if(a()){if(!i.keyCode){i.keyCode=0}if($tw.utils.checkKeyDescriptor(i,n)){l()}else if(s){e=setTimeout(l,s);o.delayTimeout=e}}}else{clearTimeout(e)}})})}};e.prototype.handleClickEvent=function(){p.apply(this,arguments);clearTimeout(this.delayTimeout);$tw.popup.cancel(Math.max(0,$tw.popup.popupInfo(this).popupLevel-1))};i.prototype.popupInfo=function(e){var t,p,i=e;while(i&&i.getAttribute){t=i.getAttribute("class")||"";p=t.indexOf("tc-preview-tiddler-");if(p>-1){t=t.substr(p).split(" ")[0];return{popupLevel:parseInt(t.charAt(t.length-1))}}i=i.parentNode}return o.apply(this,arguments)}})();