/*\
title: $:/plugins/tobibeer/preview/startup.js
type: application/javascript
module-type: startup

Enhances the link widget for on-hover previews

@preserve
\*/
(function(){"use strict";var e=require("$:/core/modules/widgets/link.js").link,t=e.prototype.render,p=e.prototype.handleClickEvent,i=require("$:/core/modules/utils/dom/popup.js").Popup,o=i.prototype.popupInfo;e.prototype.render=function(){t.apply(this,arguments);var e=this,p=this.wiki,i=this.domNodes[0],o=p.getTiddler(e.to),r="$:/plugins/tobibeer/preview/defaults/",u=$tw.utils.parseKeyDescriptor(p.getTextReference(r+"keys","").toUpperCase()),n=p.getTextReference(r+"delay").toUpperCase(),s=function(){var t=$tw.popup.popupInfo(i).popupLevel;clearTimeout(e.previewTimeout);$tw.popup.cancel(t-1);t++;p.setText("$:/temp/tobibeer/preview-"+t+"-tiddler","text",null,e.to);setTimeout(function(){$tw.popup.triggerPopup({domNode:i,title:"$:/temp/tobibeer/preview-"+t,wiki:p})},50)},l=function(){var t,o,u=1,n=p.getTextReference(r+"not","");if(n){$tw.utils.each(n.split(" "),function(e){var t=i;while(t&&u){if($tw.utils.hasClass(t,e)){u=0;return false}t=t.parentNode}})}o=p.getTextReference(r+"exclude","");t=o?p.filterTiddlers(o):[];if(t.indexOf(e.to)>=0){u=0}return u};n=n!==undefined?parseInt(n):null;if(n!==null&&isNaN(n)){n=0}if(o){$tw.utils.addClass(i,"tc-popup-handle");$tw.utils.addClass(i,"tc-popup-absolute");["mouseover","mouseout"].forEach(function(t){i.addEventListener(t,function(p){var i=p||window.event;if(t==="mouseover"){if(l()){if(!i.keyCode){i.keyCode=0}if($tw.utils.checkKeyDescriptor(i,u)){s()}else if(n!==null){e.previewTimeout=setTimeout(s,n)}}}else{clearTimeout(e.previewTimeout)}})})}};e.prototype.handleClickEvent=function(){p.apply(this,arguments);clearTimeout(this.previewTimeout);$tw.popup.cancel(Math.max(0,$tw.popup.popupInfo(this).popupLevel-1))};i.prototype.popupInfo=function(e){var t,p,i=e;while(i&&i.getAttribute){t=i.getAttribute("class")||"";p=t.indexOf("tc-preview-tiddler-");if(p>-1){t=t.substr(p).split(" ")[0];return{popupLevel:parseInt(t.charAt(t.length-1))}}i=i.parentNode}return o.apply(this,arguments)}})();